### ISSUE TITLE
 filepicker can only go three levels down in the filetree

### ISSUE THREAD

**Issue by AmalieWowern** [vnbaaij/umbraco7-filepicker#9]
The Filepicker can only go three levels down in the filetree.
![capture](https://cloud.githubusercontent.com/assets/5434989/9716719/d03b3f98-556c-11e5-94f6-18206c3bf8c9.PNG)

**Comment by AmalieWowern** [comment]
I have checked again, i cant open the last folder in filetree, i can add all the levels i want.
But the last folder will not fold out

**Comment by vnbaaij** [comment]
Amalie,
This is fixed in the latest version

**Comment by AmalieWowern** [comment]
Thanks :+1:
